#!/bin/bash

#! Name of the job:
#SBATCH -J gen_mol_array
#SBATCH -A csanyi-sl2-gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=01:00:00
#SBATCH --mail-type END
#SBATCH --mail-type FAIL
#SBATCH -p ampere
#SBATCH --array=1-20%10

# Load libraries
. /etc/profile.d/modules.sh
module purge
module load rhel8/default-amp

# Python
source ~/.bashrc
conda activate genesis

echo $PWD
PARAMETERS=$(sed -n ${SLURM_ARRAY_TASK_ID}p parameters.dat)
IFS=';' read -r -a arrIN <<<"$PARAMETERS"
python3 scripts/generate_mols.py --molecule_str ${arrIN[0]} \
    --langevin_temp ${arrIN[1]} \
    --seed ${arrIN[2]} \
    --save_path ${arrIN[3]} \
    --data_path ${arrIN[4]} \
    --num_steps ${arrIN[5]}
